// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiOUpUxsnRjmzlYA_LNR-qO28gX0tMRrI',
    appId: '1:40263552592:web:45ef30c147485f6f620b55',
    messagingSenderId: '40263552592',
    projectId: 'auctionapp-ce2ce',
    authDomain: 'auctionapp-ce2ce.firebaseapp.com',
    storageBucket: 'auctionapp-ce2ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGO2bSRwdK01UoIz90_cCp0k63_uf5RNc',
    appId: '1:40263552592:android:2639f1ce93fc3f84620b55',
    messagingSenderId: '40263552592',
    projectId: 'auctionapp-ce2ce',
    storageBucket: 'auctionapp-ce2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vbOU3G_KZJ7bSNvhUTqLnWd5QLjTsms',
    appId: '1:40263552592:ios:8f7984017dd04f23620b55',
    messagingSenderId: '40263552592',
    projectId: 'auctionapp-ce2ce',
    storageBucket: 'auctionapp-ce2ce.appspot.com',
    androidClientId: '40263552592-4b8991v915l0spi7p629g0shhem6anug.apps.googleusercontent.com',
    iosClientId: '40263552592-23a99ji40bc6eesbui425f5ft7pkdbtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-vbOU3G_KZJ7bSNvhUTqLnWd5QLjTsms',
    appId: '1:40263552592:ios:1763d14a931ac059620b55',
    messagingSenderId: '40263552592',
    projectId: 'auctionapp-ce2ce',
    storageBucket: 'auctionapp-ce2ce.appspot.com',
    androidClientId: '40263552592-4b8991v915l0spi7p629g0shhem6anug.apps.googleusercontent.com',
    iosClientId: '40263552592-agilmrgd7jam50uo4a381r80eaqo1kj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctionapp.RunnerTests',
  );
}
